name: Run CI Process for App
on: 
  workflow_call:
    inputs:
      namable-input:
        description: 'descriptor for what is passed down from calling workfrlow'
        default: './frontend'
        type: string
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup and Cache Node
        uses: actions/setup-node@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
          
      - name: Install dependencies
        run: npm install

#      - name: Create .env File
#        run: |
#          touch .env
#          echo VITE_APP_MAPBOX_TOKEN=${{ secrets.VITE_APP_MAPBOX_TOKEN }} >> .env
      
      - name: Build Dist
        run: npm run build
